site_name: Milkroute
site_description: Documentação Milkroute.
site_author: RF Solution IT

#repo_url: https://github.com/rfsolutionit/milkroute
edit_uri: ""

nav:
  - Home: index.md
  - Básico: basico.md    
  - Cadastros: cadastros.md  
  - Tarefas: tarefas.md
  - Consultas: consultas.md
  - Coleta: coleta.md
  - Produtor: produtor.md
  - Técnico: tecnico.md
  - Sobre:
    - Releases Notes: releases.md
theme: 
  name: 'flatly'

extra_css:
    - css/extra.css